# Site settings
title: Tollot's Blog
email: ptollot@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  This blog want to be a collection of what i have learned  both working as a software developer and developing
  my side projects. I will write about backend software development, and in particular about distributed systems and formal methods.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://carpino.github.io" # the base hostname & protocol for your site
twitter_username: ptollot
github_username:  carpino
linkedin_username:  pietro-tollot-32b9b320b

# Build settings
markdown: kramdown
