# Site settings
title: Tollot's Mountain Blog
email: ptollot@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is a collection of sportive and outdoor experiences and their way to them. I will also share on
  mountain hiking and any other activity or consideration regarding mountain sports and outdoor activities 
  that I will consider appropriate.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://carpino.github.io" # the base hostname & protocol for your site
instagram: "@pietrotollot"
substack: "@pinottos"

# Build settings
markdown: kramdown
